### ISSUE TITLE
Roadmap for v0.16.0

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#100]
* [x] Fix pins when already in check (#98)
* [x] Add suicide variant
* [x] Add giveaway variant
* [x] Add atomic variant
* [x] Shorten the README
* [x] Document variant support
* [x] `chess.syzygy`: Atomic tablebases
* [x] `chess.syzygy`: Suicide/giveaway tablebases
* [x] ~`chess.uci`: Automatically provide `UCI_Chess960` and `UCI_Variant`~
* [x] `chess.pgn`: Provide/parse variant header
* [x] Clean up data
* [x] Guarantee go/stop order in `chess.uci`

Maybe some more of the lichess variants:

* [x] Threecheck
* [x] Racings kings
* [x] King of the Hill
* [x] Horde
* [x] Crazyhouse

**Comment by niklasf** [comment]
Apologies to people watching this repository closely. I am doing a non-fast-forward push of master and all tags to remove big binary test assets from the past.

**Comment by niklasf** [comment]
Almost there. There's one remaining issue with suicide tablebases: http://www.talkchess.com/forum/viewtopic.php?p=697866#697866.

**Comment by niklasf** [comment]
Alright. Done :dancer:
