### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#126]
Brainstorming things I want in a stable release:

* [x] ~Consider splitting test suite~
* [x] Stable XBoard support
* [x] Complete all in-code TODOs
* [x] More performance tuning
* [x] Drop Python 2.6 support
* [x] Drop Python 2 support (#285)
* [x] Stable variants
* [x] Review documentation (including Acknowledgements, README and CHANGELOG header)
* [x] Review string representations
* [x] Code dedup for chess.gaviota
* [x] Make chess.uci API closer to asyncio (also see https://github.com/LocutusOfPenguin/picochess/blob/5774d771e1644f9aa8da23bff92fc4c4d8a8fc58/uci/engine.py from #164)
* [x] Send full history to UCI engines
* [x] Review chess.pgn tree ops
* [x] Revisit `Board._{to/from}_chess960`
* [x] Testing/acceptance of `chess.engine`
* [x] Revisit `GameCreator`
* [x] Typing (#390)
* [ ] Future of DTM tablebases

**Comment by hugovk** [comment]
+1 for dropping Python 2.6, it's long past EOL, many other libraries are dropping support and it'll get much harder to keep it around.

You could also consider ditching Python 3.3 which went EOL last month. There are fewer benefits for doing so, but it's hardly used so not so many for keeping it either.

Here's the pip installs for python-chess from PyPI for the last month:
```
$ pypinfo --percent --pip python-chess pyversion
python_version percent download_count
-------------- ------- --------------
2.7              60.9%            520
3.6              23.1%            197
3.5              13.5%            115
3.4               2.5%             21
None              0.1%              1

```

**Comment by niklasf** [comment]
Signed https://python3statement.org/. There will be no python-chess 1.0 before Python 2 support is dropped entirely.

**Comment by niklasf** [comment]
Published v0.26.0, which I plan to release as v1.0.0 soon. Just waiting until at least a handful of dependent projects have been successfully updated to ensure there are no unforseen issues.

**Comment by PedanticHacker** [comment]
1.0.0 is finally here!!! This roadmap should now close, I guess. Anyway, I'm very proud python-chess was bumped to a major version! Thanks, @niklasf, for this wonderful chess library!
